### ISSUE TITLE
Reduce Font weight

### ISSUE THREAD

**Issue by devgenix** [faradayafrica/Faraday-community#1]
Take a look at [this](https://drive.google.com/file/d/1WCJw0UnBiYdJGMXCPaGKXcnYKHKPIXDw/view?usp=sharing) and reduce the font-weight

**Comment by aniket2003** [comment]
@devgenix I would like to work on this , could you please assign me with this.

**Comment by Gluharski** [comment]
Hey, I would like to contribute. Please, assign this issue to me.

**Comment by devgenix** [comment]
> @devgenix I would like to work on this , could you please assign me with this.

Alright go ahead. Please follow the [guide to contributing](https://github.com/faradayafrica/Faraday-community#contributing)

**Comment by devgenix** [comment]
> Hey, I would like to contribute. Please, assign this issue to me.

Hey, sorry @aniket2003 indicated interest first. 
I'll mention you in the next issue, let me know if you can take that up.

**Comment by devgenix** [comment]
closed by #5
