### ISSUE TITLE
fix redirect link

### ISSUE THREAD

**Issue by devgenix** [faradayafrica/Faraday-community#2]
Take a look at [this](https://drive.google.com/file/d/1Qje8qlgM-PcTaYuW2Vci1Hr3E9GIjtQ8/view?usp=sharing)
It should redirect to https://about.faraday.africa in a new tab.

**Comment by devgenix** [comment]
@Gluharski can you take this up?

**Comment by kmartin62** [comment]
I can take it if you want

**Comment by faradayadmin** [comment]
> @Gluharski

@Gluharski please let me know if you are available to take this up as someone else is willing to.

**Comment by faradayadmin** [comment]
@kmartin62 has already worked on it. 
Thank you, I'll review it now.
